//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace battleship_client.BattleshipServerRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BattleshipServerRef.IBattleshipService", CallbackContract=typeof(battleship_client.BattleshipServerRef.IBattleshipServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IBattleshipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleshipService/Join", ReplyAction="http://tempuri.org/IBattleshipService/JoinResponse")]
        string Join(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleshipService/Join", ReplyAction="http://tempuri.org/IBattleshipService/JoinResponse")]
        System.Threading.Tasks.Task<string> JoinAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleshipService/CreateRoom", ReplyAction="http://tempuri.org/IBattleshipService/CreateRoomResponse")]
        bool CreateRoom(string name, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleshipService/CreateRoom", ReplyAction="http://tempuri.org/IBattleshipService/CreateRoomResponse")]
        System.Threading.Tasks.Task<bool> CreateRoomAsync(string name, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IBattleshipService/Leave")]
        void Leave(string name, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IBattleshipService/Leave")]
        System.Threading.Tasks.Task LeaveAsync(string name, string GUID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBattleshipServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBattleshipService/RoomAdded")]
        void RoomAdded(battleship_common.Room room);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBattleshipService/RoomDeleted")]
        void RoomDeleted(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBattleshipServiceChannel : battleship_client.BattleshipServerRef.IBattleshipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BattleshipServiceClient : System.ServiceModel.DuplexClientBase<battleship_client.BattleshipServerRef.IBattleshipService>, battleship_client.BattleshipServerRef.IBattleshipService {
        
        public BattleshipServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BattleshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BattleshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BattleshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BattleshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string Join(string name) {
            return base.Channel.Join(name);
        }
        
        public System.Threading.Tasks.Task<string> JoinAsync(string name) {
            return base.Channel.JoinAsync(name);
        }
        
        public bool CreateRoom(string name, string GUID) {
            return base.Channel.CreateRoom(name, GUID);
        }
        
        public System.Threading.Tasks.Task<bool> CreateRoomAsync(string name, string GUID) {
            return base.Channel.CreateRoomAsync(name, GUID);
        }
        
        public void Leave(string name, string GUID) {
            base.Channel.Leave(name, GUID);
        }
        
        public System.Threading.Tasks.Task LeaveAsync(string name, string GUID) {
            return base.Channel.LeaveAsync(name, GUID);
        }
    }
}
